name: Super-linter

on: workflow_dispatch

jobs:
    super-lint:
        runs-on: ubuntu-latest
        
        permissions:
            contents: read
            packages: read
            statuses: write
        
        steps:
            - uses: actions/checkout@v4
            
            - name: Super-linter
              uses: super-linter/super-linter@v4
              env:
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VALIDATE_JAVA: true
                  VALIDATE_JAVASCRIPT_ES: true
                  VALIDATE_JAVASCRIPT_STANDARD: true
